document.addEventListener("DOMContentLoaded",()=>{
 const header=document.querySelector('.header');
 const toggle=document.querySelector('.menu-toggle');
 const nav=document.querySelector('.nav-menu');
 const setHeader=()=>header&&header.classList.toggle('scrolled',window.scrollY>12);
 setHeader(); window.addEventListener('scroll',setHeader,{passive:true});
 if(toggle&&nav){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.classList.toggle('active',open);toggle.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.classList.remove('active');toggle.setAttribute('aria-expanded','false')}));}
 const page=location.pathname.split('/').pop()||'index.html'; document.querySelectorAll('.nav-menu a').forEach(a=>{if(a.getAttribute('href')===page)a.classList.add('active')});
 const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12}); document.querySelectorAll('.section,.card,.about-box,.page-hero,.property-card').forEach(el=>{el.classList.add('reveal');observer.observe(el)});
 document.querySelectorAll('[data-gallery]').forEach(gallery=>{const images=JSON.parse(gallery.dataset.gallery);const image=gallery.querySelector('.gallery-image');const dots=gallery.querySelector('.gallery-dots');let index=0; if(!dots||!image) return;images.forEach((_,i)=>{const dot=document.createElement('button');dot.className='dot'+(i===0?' active':'');dot.setAttribute('aria-label','Foto '+(i+1));dot.addEventListener('click',()=>show(i));dots.appendChild(dot)});function show(i){index=(i+images.length)%images.length;image.src=images[index];dots.querySelectorAll('.dot').forEach((d,n)=>d.classList.toggle('active',n===index))}gallery.querySelector('.gallery-prev')?.addEventListener('click',()=>show(index-1));gallery.querySelector('.gallery-next')?.addEventListener('click',()=>show(index+1));});
 const carousel=document.querySelector('[data-property-carousel]'); if(carousel){const cards=carousel.querySelectorAll('.property-card');const navDots=document.querySelector('.property-carousel-nav');let current=0;cards.forEach((card,i)=>{const dot=document.createElement('button');dot.className='dot'+(i===0?' active':'');dot.setAttribute('aria-label','Imóvel '+(i+1));dot.addEventListener('click',()=>showCard(i));navDots?.appendChild(dot)});function showCard(i){current=(i+cards.length)%cards.length;cards.forEach((c,n)=>c.style.display=n===current?'grid':'none');navDots?.querySelectorAll('.dot').forEach((d,n)=>d.classList.toggle('active',n===current));const active=cards[current];active?.classList.remove('reveal');void active?.offsetWidth;active?.classList.add('reveal','visible')}carousel.querySelector('.prev')?.addEventListener('click',()=>showCard(current-1));carousel.querySelector('.next')?.addEventListener('click',()=>showCard(current+1));showCard(0)}
});
